# .gitpod.yml

tasks:
  - init: |
      pip install jupyterlab ipykernel
      python -m ipykernel install --user --name=python3
    command: |
      jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root

ports:
  - port: 8888
    onOpen: open-preview

vscode:
  extensions:
    - ms-toolsai.jupyter
    - ms-python.python
